spring:
  application:
    name: mattrack-api
  datasource:
    url: jdbc:postgresql://localhost:5432/mattrack
    username: mattrack
    password: mattrack
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: "change-this-secret-change-this-secret-change-this-secret-256bits"
  expiration-minutes: 60

app:
  security:
    jwt:
      secret: "mattrack-secret-key-with-at-least-32-characters"
      expiration-ms: 86400000
